"""add shop_name, tax, payment_method, receipt_number, address, phone_number, notes columns to transaction

Revision ID: 2d225b7ce47c
Revises: 
Create Date: 2025-04-21 13:56:24.752749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d225b7ce47c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receipt_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')
        batch_op.drop_column('receipt_number')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('tax')
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###
